### ISSUE TITLE
Multiple AVR with different settings (setMainInputTo, inputs_as_accessories)

### ISSUE THREAD

**Issue by akke911** [NorthernMan54/homebridge-yamaha-home#11]
Hi, thanks for a great plugin!

What would a config.json look like to add 3 recivers with different settings? Mainly "inputs_as_accessories". Initialize the plugin tree times?

**Comment by NorthernMan54** [comment]
@TommyCardello Any thoughts?

**Comment by NorthernMan54** [comment]
@TommyCardello After thinking about this I'm stumped as well.  I think the way we are doing config today basically assumes all receivers have the same config, and doesn't handle that use case at all.  Or what about using the receiver name in the input as accessories config object?

**Comment by TommyCardello** [comment]
@NorthernMan54 While implementing Party Mode Switch I didn't think about using multiple receivers. 
Using the second receiver with "input_as_accessories" would be a nice and logical option. However, I didn't add any configuration to do that. At this moment it will either do nothing or break everything.

I'll try to experiment on weekends.  I'll let you know if find something interesting.

**Comment by beorn** [comment]
Independently of the multi-device control, does it support multiple devices at all?  I'm getting an error message that's maybe related?  I've got two Yamaha receivers.

```
[2018-9-18 08:52:00] [yamaha-home] Found Yamaha RX-V579 - 055ECC63, "Study Stereo"
[2018-9-18 08:52:00] [yamaha-home] Adding Party Switch Study Stereo
[2018-9-18 08:52:00] [yamaha-home] Found Yamaha RX-A3040 - 04529E83, "Lounge Stereo"
[2018-9-18 08:52:00] [yamaha-home] Adding Party Switch Lounge Stereo
[2018-9-18 08:52:11] [yamaha-home] Waited 10 seconds, stopping discovery.
[2018-9-18 08:52:11] [yamaha-home] Discovery finished, found 8 Yamaha AVR devices.
[2018-9-18 08:52:11] [yamaha-home] Initializing platform accessory 'Study Stereo'...
[2018-9-18 08:52:11] [yamaha-home] Initializing platform accessory 'Party Mode'...
[2018-9-18 08:52:11] [yamaha-home] Initializing platform accessory 'Lounge Stereo'...
[2018-9-18 08:52:11] [yamaha-home] Initializing platform accessory 'Party Mode'...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 53f477e0-b32a-433c-9ae6-3b236476fc9f
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:399:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at Timeout.timeoutFunction [as _onTimeout] (/homebridge/node_modules/homebridge-yamaha-home/index.js:148:7)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
^C
```

**Comment by beorn** [comment]
Yes, they already have different names, "Lounge Stereo" and "Study Stereo".  I see that "Party Mode" is added for both, and when I turn off party mode it continues past that, but then it runs into issues with "Main" zone being duplicate.  I guess every name related to a device has to have the device name prefixed or it won't be unique wrt HomeKit?

**Comment by TommyCardello** [comment]
@beorn Hi, your log has an error related to UUID. @akke911's advise won't work. UUID has nothing to do with receiver name. 

Here are my thoughts. I'm not a programmer, I just made a small contribution to add optional party mode an scene/input switches. So, **I'm not 100%** familiar with the whole code. 
However, I've checked the code and I see **NO restrictions** to make it work with multiple receivers. And your log shows that both your receivers have been found.

There is definitely an issue with UUID assigning.

Let's try something:
1. Please disable party mode switch and scenes/inputs optional switches from config. Just launch homebridge without those switches and see is it working. Try a sample config in the bottom of my comment.

- If it **doesn't work** even without those switches, then I would ask @NorthernMan54 for his thoughts.

- If it **works,** then I need to ask @NorthernMan54 for an advice anyway :-). That means, that my switch assigned the same UUID twice, and that's the reason for a crash. (I bet this is an issue)


Please try this step and let us know about the results.


```
{
  "platform": "yamaha-home",
  "play_volume": -48,
  "setMainInputTo": "Airplay",
  "show_input_name": "yes",
  "party_switch": "no"
}
```

**Comment by akke911** [comment]
I have 3 recivers working. You need to rename the zones, so they all are unique. 

This can be done under http://reciver ip adress/ settings rename zone

One of my recivers did not have rename zone in this settings page, but there is a special config url that can be used. Unfortunately i don't remember the url...

**Comment by akke911** [comment]
Yeah, that's what this topic is about.

Homekit don't have native sound control, so volume level is emulated as light dimmer. I changed the icon to tabletop lamp and imagine it's a fader :-)
