### ISSUE TITLE
After Configuration Restart faild

### ISSUE THREAD

**Issue by vplustute** [NorthernMan54/homebridge-yamaha-home#12]
I installed the homebridge-plugin for Yamaha AVR

For Testing I only want to use the UI Plugin und the Yamaha Plugin.

This is the Code I want to use. But wenn I use this, the Homebridge doesn't start.

`{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "XXX-XX-XXX"
    },
    "description": "This is an example configuration file for homebridge plugin for yamaha AVR",
    "hint": "Always paste into jsonlint.com validation page before starting your homebridge, saves a lot of frustration",

  "platforms": [
{
            "platform": "config",
            "name": "Config",
            "port": 8083,
            "sudo": true,
            "restart": "sudo -n systemctl restart homebridge",
            "log": "systemd"
        },
    {
      "platform": "yamaha-home",
      "play_volume": -48,
      "setMainInputTo": "Airplay",
      "show_input_name": "yes",
      "party_switch": "yes",
      "inputs_as_accessories":{
        "YamahaReceiver": {
          "1": {
                "name":"Raspberry",
                "setInputTo": "HDMI1",
                "set_default_volume": -49
           },
          "2": {
                "name":"AppleTV",
                "setInputTo": "HDMI2"
           },
           "3": {
                "name": "Scene 3",
                "set_scene": "3",
                "setInputTo": "HDMI3"
          }
        }
      },
      "manual_addresses": {
          "Yamaha": "192.168.20.9"
      }
    }
  ],
  "accessories": [
      {},
      {}
    ]
}
`

**Comment by NorthernMan54** [comment]
Can you share the error you are receiving when homebridge doesn’t start?

**Comment by vplustute** [comment]
Where I can find the error message?

**Comment by NorthernMan54** [comment]
@vplustute What program or UI are you using?   It looks like it is offering an older broken version of the plugin.   This should really be an issue raised against the UI, and not the plugin itself.

**Comment by vplustute** [comment]
It's this one of UI
Homebridge Config UI X

[https://github.com/oznu/homebridge-config-ui-x#readme](url)

**Comment by NorthernMan54** [comment]
@oznu

Any thoughts?

**Comment by vplustute** [comment]
Now I‘m using the the first one.
