### ISSUE TITLE
Access denied ?

### ISSUE THREAD

**Issue by Partizan7676** [NorthernMan54/homebridge-yamaha-home#14]
While try to install get error in logs:
39 verbose stack Error: Command failed: /usr/bin/git clone -q git://github.com/NorthernMan54/yamaha-nodejs.git /home/pi/.npm/_cacache/tmp/git-clone-c5e105f1
39 verbose stack /home/pi/.npm/_cacache/tmp/git-clone-c5e105f1/.git: Access denied

Any suggestions ?

**Comment by NorthernMan54** [comment]
Sound like a permission issue, have you tried installing with sudo?

**Comment by Partizan7676** [comment]
of course, and with unsafe-perm too. there something wrong with installation script which is try to clone git to folder root(i don,t have it). but other plugins from github or npmjs is installing correctly without any errors.
BTW Will my reciever RX-A810 work with that plugin?

**Comment by NorthernMan54** [comment]
I’m stumped as install is something that is not part of the plugin itself, but part of npm.

If your receiver uses the Yamaha av controller app, then it should work.  The plugin mimics the app’s interface

**Comment by Partizan7676** [comment]
So I install it. Only annotation about installation must be announced. User root must be enabled and installation can be done only under user root, sudo is not working

**Comment by Partizan7676** [comment]
so it is an error in installation script. i install yamaha-nodejs but plugin is not appear in homebridge
