### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by kalety** [NorthernMan54/homebridge-yamaha-home#18]
Good afternoon!, first, thank you for your very very hard work. Please, could yo explain in more detail the spotify option?. Is not clear how to put it in config.json.

Thanks in advance

**Comment by NorthernMan54** [comment]
Not sure if this attachment will work via email, but my Yamaha looks like this in the Home app



And the spotify buttons allow me to pause or skip songs when using Spotify via the receiver.

So when I’m playing music via Spotify I can quickly skip songs via Siri or Alexa ( if you have installed homebridge-alexa ).

**Comment by leotsem** [comment]
@NorthernMan54 Amazing work on this plugin!
I guess the answer is no, but can you turn on the receiver, switch to the Spotify input and start playing using the Spotify controls or does it only support pause/skip?

**Comment by NorthernMan54** [comment]
That is not possible with the plugin.

But in my setup, I’m using Alexa to control everything and have an Alexa routine that does most of this.

**Comment by leotsem** [comment]
Given your experience interacting with the Yamaha interface, do you know if it’s possible to implement something like this? 
If so, I’m happy to have a look and perhaps send a PR.

**Comment by NorthernMan54** [comment]
@leotsem Just thinking further about this, and you may be able to do this without changing the plugin.  As the plugin will allow you to turn on the receiver, change the input to Spotify and press play on the Spotify play button.  I just not sure about the behaviour with the Spotify play button.

As I indicated earlier, I'm doing this with an Alexa routine.  I'm not sure if HomeKit automations allow you to execute these in order.
