### ISSUE TITLE
Yamaha AVR shows up as lightbulb and is named Main

### ISSUE THREAD

**Issue by theodorjs** [NorthernMan54/homebridge-yamaha-home#19]
The Yamaha plugin is not working as expected for me. When running Homebridge in Debug mode, I can see that every function of the AVR is discovered and listed, but it still shows up as a lightbulb in the end.

Here is the excerpt from config.json:
"platform": "yamaha-home",
          "play_volume": -48,
          "setMainInputTo": "AV4",
          "show_input_name": "yes",
          "manual_addresses": {
              "HTR-4065-91A959": "192.168.1.18"

![screen shot 2018-11-13 at 00 30 18](https://user-images.githubusercontent.com/44986321/48381438-1a1b7200-e6dc-11e8-8fb9-9f76f97cfdbd.png)

**Comment by NorthernMan54** [comment]
Showing up as a lightbulb is by design, as HomeKit and the home app don’t support a stereo yet.

Turning on/off the light bulb, should turn on and off the stereo and the brightness is volume.

**Comment by theodorjs** [comment]
Thank you for replying! I’m glad everything is working as intended then.
