### ISSUE TITLE
NET RADIO bookmark setup

### ISSUE THREAD

**Issue by rap165** [NorthernMan54/homebridge-yamaha-home#22]
Hi yamaha-home,
Splendid project and kudos for the work, I now have my RX-V575 in my homekit and it works fine, yet I'm a big fan of web/netradio and can't get my favourite bookmark to load ([Radio Nova Paris](http://www.nova.fr)!) when I change Scene or input. Can this be done? If yes, can you provide me an example of the config? 
Again, thanks!
Cheers,

**Comment by NorthernMan54** [comment]
Unfortunately that feature is not supported by plugin.
