### ISSUE TITLE
problem with instal

### ISSUE THREAD

**Issue by seokrs** [NorthernMan54/homebridge-yamaha-home#24]
Im getting this answer upon instal.. any suggestions?

pi@raspberrypi:~ $ sudo npm install -g homebridge-yamaha-home
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/NorthernMan54/yamaha-nodejs.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by NorthernMan54** [comment]
Please try the install again
