### ISSUE TITLE
Volume control is gone since last update

### ISSUE THREAD

**Issue by albi** [NorthernMan54/homebridge-yamaha-home#25]
The quite useful volume control is gone since the last update today. Is it a bug?

**Comment by NorthernMan54** [comment]
That is really weird as the code I promoted yesterday was just a backend package version issue, and nothing to do with the devices created.  Are you sure you were using this version?  This version is optimized to have zones appear as light bulbs.

**Comment by albi** [comment]
Yep volume control is gone. I did not change the settings, I've just restarted homebridge after the update. My settings are:

`
{
    "platform": "yamaha-home",
    "play_volume": -30,
    "setMainInputTo": "Airplay",
    "show_input_name": "yes",
    "expected_devices": 2,
    "inputs_as_accessories": {
        "YamahaReceiver": {
            "1": {
                "name": "▶ TV",
                "setInputTo": "Optical",
                "set_default_volume": -30
            },
            "2": {
                "name": "▶ AirPlay",
                "setInputTo": "AirPlay",
                "set_default_volume": -30
            }
        }
    },
    "manual_addresses": {
        "Yamaha": "10.0.1.8"
    }
},
`

The accessories are still switches not light bulbs right?

**Comment by albi** [comment]
I even did a reboot of the Raspi. Still no volume control available :-(

**Comment by NorthernMan54** [comment]
@albi I'm a bit lost when it comes to a volume control, as I have been using it as a light bulb.  But the older versions are still available.  You can see the versions here

https://github.com/NorthernMan54/homebridge-yamaha-home/commits/master

And can install just by specifying the version as part of npm install ie

sudo npm install -g homebridge-yamaha-home@0.0.29

This is the previous version

**Comment by albi** [comment]
Thanks for your reply. Going back to v0.0.29 or v0.0.30 does not work for me. I tried to "sudo npm install -g --unsafe-perm homebridge-yamaha-home@0.0.30" with or without --unsafe-perm it won't work.

The error looks like:

`npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-f49e0e84': Keine Berechtigung
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-21T08_15_55_056Z-debug.log
`

The error "Keine Berechtigung" is no like "not allowed".

But the main problem still exists. The volume control was indeed a light bulb that I was able to force touch on my iOS devices to select the volume from 0% to 100%. This control is just gone. All other controls like switching to an input like optical or AirPlay still works.

Unfortunately I do not have a screenshot of the old light bulb volume control. :(

**Comment by albi** [comment]
Actually I've managed to get back the light bulb control with the homebridge-yamaha_mc2 Plugin :)

**Comment by radiomurf** [comment]
0.0.31 also broke this plugin for me. Reinstall of 0.0.30 fixed the issue.

**Comment by NorthernMan54** [comment]
Not sure what is wrong, but I rolled back the latest commit 0.0.33 is just 0.0.30

**Comment by NorthernMan54** [comment]
I did some

**Comment by NorthernMan54** [comment]
I did some more digging, and one of the upstream packages has a bad version.  I have opened a ticket with them to resolve.

https://github.com/PSeitz/yamaha-nodejs/issues/25

**Comment by NorthernMan54** [comment]
This has been resolved with today's update
