### ISSUE TITLE
Light bulb icon

### ISSUE THREAD

**Issue by robboz4** [NorthernMan54/homebridge-yamaha-home#27]
Hi! 
I just added this plugin to my home bridge set up. I used the example config as a test. It worked without any issues. My only question is that the icon in homebridge is a light bulb. So changing the "brightness" is actually the volume control. Is this the correct icon set up?

As radio_presets  and preset_num are true I thought I would see the preset radio channel buttons. Am I missing something on the config set up?

Thanks for the writing the plugin!

**Comment by NorthernMan54** [comment]
When I built this plugin, I was limited to the available HomeKit icons at the time.  So the receiver/zone is a lightbulb, where the brightness is the volume.  Once HomeKit/homebridge supports speakers I will be updating.

For the preset names, try preset_num false.  It should use the radio channel as the button names.

**Comment by robboz4** [comment]
Thanks for the quick reply and explanation.

I tried your suggestion but still no channels. I wonder if my Yamaha RX-V473 be a bit too old?
I've had it for a good few years. Anyway power and volume work just fine.

Thanks!

**Comment by NorthernMan54** [comment]
Your welcome

**Comment by reiterbene** [comment]
@NorthernMan54 HomeKit support TVs from now on (iOS 12.2) and as the Receiver has a lot of the same functionalities (Input selection, Volume, Power, Play/Pause, ...) it may suite quite well to the needs of this Homebridge Plugin.

[merdok/homebridge-webos-tv](https://github.com/merdok/homebridge-webos-tv) already supports it for instance.

**Comment by NorthernMan54** [comment]
I have been watching those developments, and once the iOS beta is published I will be taking a look at this, stay tuned.

**Comment by NorthernMan54** [comment]
@reiterbene I published Yamaha-Zone-TV, with support of iOS 12.2 TV Devices.  Take a look
