### ISSUE TITLE
Fan Icon

### ISSUE THREAD

**Issue by Trippersgarage** [NorthernMan54/homebridge-yamaha-home#30]
Not sure whats happened but my AVR is now suddenly showing up with a fan icon after the latest update? Cant change it in my home app. Is this by design?

**Comment by NorthernMan54** [comment]
Yes it was by design, as I found that if you ask Siri to turn on or off all the lights she was turning on and off the stereo as well.

Besides the icon issue, no change in functionality.

**Comment by Trippersgarage** [comment]
Makes sense. Thanks for the explanation.

**Comment by alejandrofdez-us** [comment]
Is it possible to speed up the volume increasing/decreasing? Seems that as it is considered a fan, homekit increases and decreases its "speed" (volume) slowly.

**Comment by NorthernMan54** [comment]
Can you explain what your doing to raise and lower the volume?   Please keep in mind that the plugin uses a formula to map a single % change to a volume change on the receiver.  And if you change max and min volume it how fast it moves
