### ISSUE TITLE
conflict with another home bridge component

### ISSUE THREAD

**Issue by deadbone** [NorthernMan54/homebridge-yamaha-home#32]
Hi, I'm using this plugin since the one I used had some failure. 
The plug-in works great but ... strange thing, I use the Dyson homebridge plugin for my fan and when I use Siri to shutting down the fan, my AVR is shutting down too :)
Is there a way  to bypass this behavior ?
Thanks

**Comment by NorthernMan54** [comment]
Check your wording with Siri, saying all fans etc may cause this

**Comment by deadbone** [comment]
OK, I’ll try that
Thanks
