### ISSUE TITLE
subwoofer switch

### ISSUE THREAD

**Issue by netRunner0** [NorthernMan54/homebridge-yamaha-home#33]
Hello! Can I make a switch to enable / disable subwoofer or sound modes?

**Comment by NorthernMan54** [comment]
Yes you can, it will require some coding but you could.  If you wanted to submit a pull request with the changes much appreciated.

**Comment by netRunner0** [comment]
I can not write code :)

**Comment by NorthernMan54** [comment]
Sorry without someone writing some code it won’t support the features.  Support for various Features  has been added by people in the community.

**Comment by netRunner0** [comment]
https://github.com/PSeitz/yamaha-nodejs

And it can not be used?

**Comment by NorthernMan54** [comment]
If you look at the plugin internals, it uses this to interface between homebridge and the receiver.
