### ISSUE TITLE
Inputs as accessories are gone since last update

### ISSUE THREAD

**Issue by albi** [NorthernMan54/homebridge-yamaha-home#35]
My two inputs, one for AirPlay the other one for Optical are gone since the update to 0.1.10. As far I can see you've changed something for the inputs as accessories.

**Comment by NorthernMan54** [comment]
As part of fixing #34 I had tweaked the way the configuration works to match the readme.  In your config, change “YamahaReceiver” to be your receiver name

**Comment by albi** [comment]
But what is the name? The networkname I've set or the model name of the receiver?
