### ISSUE TITLE
Device not being added as an accessory

### ISSUE THREAD

**Issue by alexgarden** [NorthernMan54/homebridge-yamaha-home#37]
I recently added a Yamaha WX-021 (MusicCast 20) as a wireless speaker for a new room in my house.  All the other zones which are being driven of WXA-50's or RX-V685's are working as expected.

The device is being discovered:
`[5/22/2020, 11:03:15 AM] [yamaha-home] Possible Yamaha device discovered Bathroom [ '10.0.0.20', 'fe80::7add:12ff:fe15:5f91' ]`

In the config, I'm making an explicit allowance for it:
`"zone_controllers_only_for": "Living, Kitchen, Main, Office, Master, Dining, Deck, Bathroom",`

Despite that, no Zone Controller is assigned by the plugin, leading to no device accessory being created.

The WX-021 is adopted into the MusicCast network but is not a child of any other device.  

Thoughts?

**Comment by NorthernMan54** [comment]
This plugin uses the web site put out by the receiver to control it.  Does your WX-021 have a web site similar to the receiver?

**Comment by alexgarden** [comment]
Yes it does.  On my network, the WX-021 ("Bathroom") is at `10.0.0.20`.  If I open an HTTP connection to that address I see a web console with all the functionality of my other endpoints.

Additionally, the WX-021 shows up as a fully-qualified room in the MusicCast control app with it's own transport controls, etc.

In the log, it seems a device goes through three states:

1. `Possible Yamaha device discovered`
2. 'Found <device_type>'
3. 'Initializing platform accessory'

In this case, the WX-021 only completes the first step.  I piped the SysConfig call in `setupFromService` to the log and confirmed that for each of the other accessories I see a full information package, but for the WX-021 I see this:

`[5/23/2020, 7:36:20 AM] [yamaha-home] [SysConfig -> Bathroom -> null`

So... It looks like in `simpleCommands.js` in the function `getSystemConfig` that this snippet results in an invalid polling result only from the WX-021:

`var command = '<YAMAHA_AV cmd="GET"><System><Config>GetParam</Config></System></YAMAHA_AV>';
    return this.SendXMLToReceiver(command).then(xml2js.parseStringAsync);`

This is odd behavior because all the Yamaha native apps think of the WX-021 as a peer to all the other system devices.

Thoughts?

**Comment by NorthernMan54** [comment]
The 'WX-021' doesn't support the API used by this plugin.

**Comment by alexgarden** [comment]
Aaaah... Thanks for letting me know.

Given Yamaha is moving in this direction, the logical next question is, "What API does the WX-??? family use?"  They clearly have a full set of API controls as the MusicCast app treats this device in the same way as any other Yamaha device.  It would be great if we were able to add API support for the new family of devices.

Thoughts?

.a

________________________________

**Comment by NorthernMan54** [comment]
Adding support would need a developer with access to the appropriate devices.  If someone wants to submit this as a pull request I would gladly publish

**Comment by alexgarden** [comment]
I have access to the devices.  😉 What do you need specifically?  Assume just the HTTP controls?  Are these published anywhere or do I need to sniff them?

________________________________

**Comment by alexgarden** [comment]
I'm personally baffled as to why Yamaha would have these devices inaccessible via the API they use for the rest of their networked AV gear but who am I to question why.

Fortunately, there seems to be a workaround here.  By installing the following two plugins you can effectively replicate the desired behavior:

1. For device power, install `Musiccast Tv`.  In my case, the only input I enumerate is "mc_link" as I'm using this room as a member of a housewide playgroup where I only need to turn it on and off and modify its volume depending on the scene I'm selecting.

2. For device volume, install `Yamaha MC3`.

Fun fact: You can directly add the WX-021 to Homekit as a speaker BUT you are unable to modify it's status *unless* you're playing to it from iTunes (thanks, Apple) so that is a useless tease.

This issue can be closed, although the OCD part of me would sure love it if I could drop the two hack-plugin installs and use `Yamaha Home` for everything.
