### ISSUE TITLE
Issue with multiple receivers

### ISSUE THREAD

**Issue by alexgarden** [NorthernMan54/homebridge-yamaha-home#38]
Let me first say, I love this plugin lest I become a pest.

If you have multiple MusicCast devices it's necessary to create a play group for them to get them to play synchronous music.  You do this in the MusicCast app on a mobile device.

If you do not create zones for each device, you can still expose each MusicCast device as an accessory, however, when you change the volume on that device it will drop out of the play-group, effectively killing the music to that device.

The way around that is to create a zone for each device.  So far so good.  Here is an issue though:

Yamaha receivers register as "Main" regardless of what network name they are given.  This works (although it is confusing) when you only have one receiver.  I have two now and that causes them to error out on init as they both register with "Main".

A solution to this is to always register a device with it's network name, regardless of the device type.  This way, as long as the administrator uses a unique network name for a device all will work well.

Is it possible to make this change?

**Comment by NorthernMan54** [comment]
Just go into the Yamaha receiver config and change the name to something more meaningful than "Main". I have my zones named as front and rear

**Comment by alexgarden** [comment]
As hard as I have tried, I'm getting two persistent issues:

1) On my RX-S601 for the life of me I am unable to find any utility for renaming zones.  I have tried the web interface, the MusicCast app, and the AV Controller app and the OSD.  Is there a command-line?  SSH?

2) On my RX-V685 I was able to rename Zone 1 to "Family", which would allow me to leave the RX-S601 in the garage named, "Main" without the collision however for reasons I can't explain, the RX-V685 still reports "Main" as its name so the collision keeps happening.

Thoughts?

.a

________________________________

**Comment by alexgarden** [comment]
On this particular issue, the RX-S601 doesn't support renaming the zones beyond "Main" and "Zone 2".  

Fortunately, the RX-V685 does support this, but only using the OSD.  This is confusing because you can rename zones in the MusicCast app, but it appears this only changes the descriptive name of the zone, not the logical name.

This issue can be closed.
