### ISSUE TITLE
Two Zone set up help with config

### ISSUE THREAD

**Issue by commet101** [NorthernMan54/homebridge-yamaha-home#39]
Hello,

First I want to thank you for making this! It is great. I am very new to homebridge/plugins and cannot figure out how to configure this to work with two zones. I've tinkered with it for hours but can only get it to identify my main zone. I have a RX-V583 with a Zone A (main zone) and a Zone B set up. Any guidance you could provide in how to configure and set up two zones would be greatly appreciated. I also went through previous issues before posting this to see if I could find anything similar, but everything I have tried hasn't worked. I see that "zone" is configurable, but I can never get it to identify my second zone. My current config doesn't have any "zone" because I just couldn't get it them to work.

Below is my current config: 

{
            "platform": "yamaha-home",
            "discovery_timeout": 25,
            "play_volume": -30,
            "setMainInputTo": "Av1",
            "show_input_name": "yes",
            "inputs_as_accessories": {
                "Yamaha": {
                    "1": {
                        "name": "TV",
                        "set_scene": "2"
                    },
                    "2": {
                        "name": "Radio",
                        "set_scene": "4"
                    }
                }
            },
            "manual_addresses": {
                "Yamaha": "192.168.1.16"
            }
        }

**Comment by NorthernMan54** [comment]
My config from my rxv1075 looks like this

```
{
  "platform": "yamaha-home",
  "discovery_timeout": 5,
  "radio_presets": true,
  "preset_num": true,
  "max_volume": 20,
  "party_switch": "yes",
  "spotify": true,
  "inputs_as_accessories": {
    "YamahaReceiver": {
      "1": {
        "name": "Input Radio",
        "setInputTo": "TUNER"
      },
      "2": {
        "name": "Input Spotify",
        "setInputTo": "Spotify"
      },
      "3": {
        "name": "Input AV1",
        "setInputTo": "AV1"
      }
    }
  }
```

If you run Homebridge in DEBUG mode, the plugin will log more details on your receiver and might expose why it is having issues

If you start Homebridge like this

DEBUG=* homebridge

The log will include a lot more detail, and what's of interest are the lines with "yamaha-home"
