### ISSUE TITLE
Accessories Missing from Homekit After Every Mac Reboot

### ISSUE THREAD

**Issue by proactivematter** [NorthernMan54/homebridge-yamaha-home#41]
Hey @NorthernMan54,

I run Homebridge from my Mac, and lately I've noticed homebridge-yamaha-home accessories will disappear from homekit everytime I reboot the computer. This means that my homekit looses all room assignments / scenes for the AVR.

To get the accessories to initialize properly, I have to restart homebridge.

I've only 1 other homebridge plugin I currently use - homebridge-bravia-tvos v3.0.7 - and that one does not disappear, so I guess this is either an issue or limitation of your plugin.

Here's what I'm seeing in the log after rebooting the computer:

[8/27/2020, 5:59:46 PM] [yamaha-home] Initializing yamaha-home platform...
[8/27/2020, 5:59:46 PM] [yamaha-home] Getting Yamaha AVR devices.
[8/27/2020, 5:59:46 PM] [yamaha-home] Possible Yamaha device discovered RX-V583 (Wireless) undefined
[8/27/2020, 5:59:46 PM] [yamaha-home] DEBUG: Failed getSystemConfig from RX-V583 (Wireless), probably just not a Yamaha AVR.
[8/27/2020, 6:00:53 PM] [yamaha-home] Waited 10 seconds, stopping discovery.
[8/27/2020, 6:00:53 PM] [yamaha-home] Discovery finished, found 0 Yamaha AVR devices.

As a side note, I do not have discovery_timeout set, yet it says it is only waiting for 10 seconds. The documentation says the default is supposed to be 30 secs. That said, I have tried setting it to 60 secs to see if the AVR is detected, but no success.

Thanks for the help. Let me know if you need anything from me in order to figure this out.

**Comment by albi** [comment]
Same here on a Raspi. On a reboot, there is a lot missing afterwards. Have to setup names, reassign rooms and setup scenes.

**Comment by NorthernMan54** [comment]
This is a very odd bug report as I spent the weekend trying to recreate this issue without any luck.  The only comment I would make is that I'm running this plugin in its own instance of homebridge, but I don't think that makes a difference

**Comment by proactivematter** [comment]
Thanks NorthernMan54. I will try doing that and will report back.

I dunno if you came across this, but a user of another plugin who was
experiencing a similar issue reports that running the plugin in a dedicated
instance was a valid workaround for him:

https://github.com/nfarina/homebridge/issues/1434

**Comment by albi** [comment]
One thing I can say for sure. If the device is not available on the network (like having it disconncted), and then reboot your Raspberry, the device would be gone from Homebridge.

**Comment by proactivematter** [comment]
Alright, so I set up a second Homebridge instance and indeed the problem persists.

However, I did notice the logs produced more information this time around for whatever reason (I dunno, maybe I just missed it last time). Take a look:

[9/12/2020, 10:42:23 AM] [yamaha-home] Initializing yamaha-home platform...
[9/12/2020, 10:42:23 AM] [yamaha-home] Getting Yamaha AVR devices.
[9/12/2020, 10:42:23 AM] [yamaha-home] Possible Yamaha device discovered RX-V583 (Wireless) undefined
OperationalError: connect ENETUNREACH 192.168.2.10:80 - Local (0.0.0.0:49158)
    at internalConnect (net.js:923:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:351:12)
    at net.js:1011:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  cause: Error: connect ENETUNREACH 192.168.2.10:80 - Local (0.0.0.0:49158)
      at internalConnect (net.js:923:16)
      at defaultTriggerAsyncIdScope (internal/async_hooks.js:351:12)
      at net.js:1011:9
      at processTicksAndRejections (internal/process/task_queues.js:79:11) {
    errno: 'ENETUNREACH',
    code: 'ENETUNREACH',
    syscall: 'connect',
    address: '192.168.2.10',
    port: 80
  },
  isOperational: true,
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.2.10',
  port: 80
}
[9/12/2020, 10:42:23 AM] [yamaha-home] DEBUG: Failed getSystemConfig from RX-V583 (Wireless), probably just not a Yamaha AVR.
[9/12/2020, 10:42:40 AM] [yamaha-home] Waited 10 seconds, stopping discovery.
[9/12/2020, 10:42:40 AM] [yamaha-home] Discovery finished, found 0 Yamaha AVR devices.

**Comment by NorthernMan54** [comment]
That looks like it is trying to talk to a Yamaha device at 192.168.2.10, but it isn’t answering

**Comment by proactivematter** [comment]
Hm. Alright, thanks NorthernMan54. I guess for now I'll just have so set up an rpi+UPS if I want to avoid this issue.

**Comment by proactivematter** [comment]
Last consideration, when yamaha-home connects to the AVR, I always get the following:

`[9/14/2020, 11:43:01 AM] [yamaha-home] WARN: Got multiple systems with ID 0DABE453! Omitting duplicate!`

Why does it happen? Could it be related to this issue?

**Comment by NorthernMan54** [comment]
Looking at the name it appears to a different device that isn't a Yamaha device.

**Comment by albi** [comment]
Still having the problem. If I restart Homebridge and the Yamaha is not available at the moment (switches completely off because of energy saving) the switches from this plugin will disappear.

If I switch the Yamaha receiver on and then restart Homebridge, the switches are still available.

Is there something you could do to make those switches persistent?

**Comment by NorthernMan54** [comment]
@albi This plugin was written and designed around the concept of minimal config and auto discovery of receivers, and it does not retain any details of receivers.  To change the design would require re-writing the plugin, and I don't have the free time at the present to take this on.
