### ISSUE TITLE
Scene-Switches are auto-switched on after some time.

### ISSUE THREAD

**Issue by marvelousmo** [NorthernMan54/homebridge-yamaha-home#42]
Hello,

I configured 8 scenes in my Yamaha-Receiver and they work fine so far with homebridge. But after some time all of these 8 scenes have the "switched-on" appearance in my homekit app although I never switched them on. What could I do about it?

Thank you very much!

{
    "platform": "yamaha-home",
    "radio_presets": true,
    "inputs_as_accessories": {
        "Yamaha": {
            "1": {
                "setInputTo": "Spotify",
                "set_scene": "1",
                "name": "All Out of 80s"
            },
            "2": {
                "setInputTo": "Spotify",
                "set_scene": "2",
                "name": "Classic Road Trip"
            },
            "3": {
                "setInputTo": "Spotify",
                "set_scene": "3",
                "name": "Chill As Folk"
            },
            "4": {
                "setInputTo": "Spotify",
                "set_scene": "4",
                "name": "Jazz in the Background"
            },
            "5": {
                "setInputTo": "Spotify",
                "set_scene": "5",
                "name": "Slow Guitar Acoustic"
            },
            "6": {
                "setInputTo": "Spotify",
                "set_scene": "6",
                "name": "Surf Chill"
            },
            "7": {
                "setInputTo": "Spotify",
                "set_scene": "7",
                "name": "Wake Up Gently"
            },
            "8": {
                "setInputTo": "Spotify",
                "set_scene": "8",
                "name": "Floating Through Space"
            }
        }
    }
}

**Comment by NorthernMan54** [comment]
That section of code was an add on from @TommyCardello a few years ago, maybe he can comment on this.

I looked at it briefly and can see what the challenge is.  The switches are set 'On' based on the current input, so when Spotify is the input, they will all turn on.

**Comment by marvelousmo** [comment]
aaah I see! Well that‘s a pitty, but probably someone can provide a solution..

Thank you very much so far!
