### ISSUE TITLE
Selecting Zones and input

### ISSUE THREAD

**Issue by tbb-rx-a3080** [NorthernMan54/homebridge-yamaha-home#45]
Can someone please post an example of a config file that supports multiple zones?  I have a RX-A3080 with 4 zones.  I would like to be able to set an accessory for SiriusXM-Zone3 which would then:
1. Turn on Zone 3
2. Set the input to SiriusXM
3. Without affecting the other zones

When I click on the SiriusXM accessory now, it sets it for all zones instead of just Zone 3.  Also, when I click on Apple TV, it switches it on the Receiver, but the accessory button in HomeKit flashes on and then off.  

Here is my config:
{
    "platform": "yamaha-home",
    "radio_presets": true,
    "play_volume": -48,
    "setMainInputTo": "AppleTV",
    "show_input_name": "yes",
    "party_switch": "yes",
    "expected_devices": 100,
    "manual_addresses": {
        "Yamaha": "192.168.1.28"
    },
    "inputs_as_accessories": {
        "Yamaha": {
            "1": {
                "name": "SiriusXM",
                "zone": "Zone3",
                "setInputTo": "SiriusXM",
                "set_default_volume": -49,
                "show_input_name": "yes"
            },
            "2": {
                "name": "Input Radio",
                "setInputTo": "TUNER",
                "set_scene": 2
            },
            "3": {
                "name": "Scene 3",
                "set_scene": 3,
                "setInputTo": "HDMI3"
            },
            "4": {
                "name": "Pandora",
                "zone": "Zone2",
                "setInputTo": "Pandora",
                "set_default_volume": -49,
                "show_input_name": "yes"
            },
            "7": {
                "name": "Apple TV",
                "setInputTo": "Apple TV",
                "zone": "Main"
            }
        }
    }
}

**Comment by Bankaifan** [comment]
Can we expect any reply on this? Having the same issues. All accessories in HomeKit stay offline and setting the Zone does not work

**Comment by Bankaifan** [comment]
@tbb-rx-a3080 are you still having this problem? I am working on a fork - however, you can give this a try:
Use "Zone_3" oder simple 1, 2, 3 for you zones. This should work better.
