### ISSUE TITLE
Use Siri to Change Volume

### ISSUE THREAD

**Issue by bjornand1** [NorthernMan54/homebridge-yamaha-home#46]
Hi, I have been looking for a way to tell Siri (on my HomePod Mini) to turn up or down the volume on the Yamaha Receiver. This plugin works perfectly using the Home app, where adjusting the "fan speed" changes the receiver volume. However, trying all kinds of versions of commands to use my voice to tell siri to change the volume (fan speed) or set it to a certain level, I can not get it to work. Siri will say she is on it or something similar, but will never succeed in changing the volume.

Is this a HomeKit limitation or am I missing something about this can be done?

**Comment by bjornand1** [comment]
Sorry, a few additional permutations of words, and I got it to work. For anyone curious, this works for mer: Hei, Siri, set the living room TV to 40 percent.

**Comment by NorthernMan54** [comment]
If your so inclined you could add your discovery to the README via a pull request.  Just select the pen icon at the top right of the README, and it will open an editor and walk you thru a pull request.
